---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  build: ${NAME}
  template: "${NAME}-bc-template"
  name: ${NAME}-prod
metadata:
  name: ${NAME}
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        shared: "true"
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}${SUFFIX}
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      successfulBuildsHistoryLimit: 3
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      postCommit: {}
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      runPolicy: SerialLatestOnly
      source:
        contextDir: tools/jenkins/docker
        git:
          ref: ${SOURCE_REPO_REF}
          uri: ${SOURCE_REPO_URL}
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins:2
            namespace: openshift
        type: Docker
    triggers:
      - type: ImageChange
        imageChange: {}
parameters:
  - name: NAME
    description: Application name used for all objects
    displayName: Name
    required: true
    value: jenkins
  - name: SUFFIX
    description: An optional suffix used for all objects
    displayName: Suffix
    required: false
    value: ""
  - name: VERSION
    description: The version name of the output image tag
    displayName: version
    required: true
    value: latest
  - name: SOURCE_REPO_REF
    description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
    displayName: Source Repository Reference
    required: false
    value: master
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    displayName: Source Repository URL
    required: true
